language: node_js

node_js:
  - "0.12"

install:
  # Install Hexo
  - npm install hexo-cli -g
  # Install dependencies
  - npm install

script:
  - hexo generate && hexo deploy

branches:
  only:
    - master