menu:
  首页: /
  #文章归档: /archives
  #相册: /photo
  #友情链接: /links
  #关于: /about

excerpt_link: 阅读全文 >

google_analytics: UA-61760358-1

rss: /atom.xml

comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: hengdev
